version: '3.8'

services:
  db:
    image: mariadb
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_DATABASE: 'mariadb'
      MYSQL_USER: 'rootuser'
      MYSQL_PASSWORD: 'rootpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mariadb
# Names our volume
volumes:
  my-db: